name: "Jira Task Check GitHub Action"
description: "A GitHub Action that checks if a pull request closing an issue mentions a Jira task."
branding:
  icon: "check-circle"
inputs:
  github-token:
    description: "GitHub token for authentication and accessing the API."
    required: true
    default: "${{ github.token }}"
runs:
  using: "node16"
  main: "index.js"
